services:
  server1:
    container_name: server1
    image: pong_server  # This can be omitted.
    build: .
    environment:
      - OTHER_SERVICE_ADDRESS=server2
      - PORT=8001
    ports:
      - '8001:8001'
  server2:
    container_name: server2
    image: pong_server  # This can be omitted.
    build: .
    environment:
      - OTHER_SERVICE_ADDRESS=server1
      - PORT=8002
    ports:
      - '8002:8002'
